### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rohanpsingh** [gergondet/mc_rtc-magnum#1]
Hi @gergondet ,

Following your recommendation [here](https://github.com/jrl-umi3218/mc_rtc/issues/160#issuecomment-873772932),  
I tried to build this project, as a first step.  
But first the following error:
```

In file included from /home/rohan/src/mc_rtc_magnum/src/widgets/../McRtcGui.h:6:0,
                 from /home/rohan/src/mc_rtc_magnum/src/widgets/Widget.h:5,
                 from /home/rohan/src/mc_rtc_magnum/src/widgets/Robot.h:3,
                 from /home/rohan/src/mc_rtc_magnum/src/widgets/Robot.cpp:1:
/home/rohan/src/mc_rtc_magnum/src/widgets/../MagnumClient.h:80:8: error: ‘void mc_rtc::magnum::MagnumClient::visual(const ElementId&, const rbd::parsers::Visual&, const PTransformd&)’ marked ‘override’, but does not override
   void visual(const ElementId & id, const rbd::parsers::Visual & visual, const sva::PTransformd & pos) override;
```

I'd be glad if you could help me out, thanks!

**Comment by gergondet** [comment]
Hi @rohanpsingh 

It seems like you are using an older version of mc_rtc. This was added in https://github.com/jrl-umi3218/mc_rtc/pull/157

Updating mc_rtc should do the job

**Comment by rohanpsingh** [comment]
Thanks, it is solved after updating mc_rtc~!
